<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Employee;
use App\Models\Position;
use App\Models\User;
use Illuminate\Database\Seeder;

class EmployeesSeeder extends Seeder
{
    public function run(): void
    {
        $tiDept = Department::where('code', 'TI')->first();
        $rhDept = Department::where('code', 'RH')->first();
        $venDept = Department::where('code', 'VEN')->first();
        $finDept = Department::where('code', 'FIN')->first();
        $mktDept = Department::where('code', 'MKT')->first();

        $employees = [
            [
                'employee_number' => 'EMP-001',
                'first_name' => 'Carlos',
                'last_name' => 'Rodríguez Méndez',
                'email' => 'carlos.rodriguez@baglass.com',
                'phone' => '(55) 2345-6789',
                'mobile' => '(55) 1111-2222',
                'curp' => 'ROMC850615HDFRRL09',
                'rfc' => 'ROMC850615ABC',
                'birth_date' => '1985-06-15',
                'hire_date' => '2018-03-01',
                'department_code' => 'TI',
                'position_code' => 'GER-TI',
                'user_email' => 'carlos.rodriguez@baglass.com',
                'address' => 'Av. Revolución #456',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '03100',
            ],
            [
                'employee_number' => 'EMP-002',
                'first_name' => 'Laura',
                'last_name' => 'Martínez González',
                'email' => 'laura.martinez@baglass.com',
                'phone' => '(55) 3456-7890',
                'mobile' => '(55) 2222-3333',
                'curp' => 'MAGL880920MDFRRL05',
                'rfc' => 'MAGL880920XYZ',
                'birth_date' => '1988-09-20',
                'hire_date' => '2019-06-15',
                'department_code' => 'RH',
                'position_code' => 'GER-RH',
                'user_email' => 'laura.martinez@baglass.com',
                'address' => 'Calle Insurgentes #789',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '06600',
            ],
            [
                'employee_number' => 'EMP-003',
                'first_name' => 'Miguel Ángel',
                'last_name' => 'Hernández',
                'email' => 'miguel.hernandez@baglass.com',
                'phone' => '(55) 4567-8901',
                'mobile' => '(55) 3333-4444',
                'curp' => 'HEMM900312HDFRNL08',
                'rfc' => 'HEMM900312DEF',
                'birth_date' => '1990-03-12',
                'hire_date' => '2020-01-15',
                'department_code' => 'TI',
                'position_code' => 'DEV-SR',
                'user_email' => 'miguel.hernandez@baglass.com',
                'address' => 'Blvd. Reforma #123',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '11560',
            ],
            [
                'employee_number' => 'EMP-004',
                'first_name' => 'Ana Patricia',
                'last_name' => 'López',
                'email' => 'ana.lopez@baglass.com',
                'phone' => '(55) 5678-9012',
                'mobile' => '(55) 4444-5555',
                'curp' => 'LOAA920725MDFPNN02',
                'rfc' => 'LOAA920725GHI',
                'birth_date' => '1992-07-25',
                'hire_date' => '2021-03-01',
                'department_code' => 'VEN',
                'position_code' => 'EJEC-VEN',
                'user_email' => 'ana.lopez@baglass.com',
                'address' => 'Av. Universidad #456',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '04510',
            ],
            [
                'employee_number' => 'EMP-005',
                'first_name' => 'Roberto',
                'last_name' => 'García Sánchez',
                'email' => 'roberto.garcia@baglass.com',
                'phone' => '(55) 6789-0123',
                'mobile' => '(55) 5555-6666',
                'curp' => 'GASR870418HDFRBN07',
                'rfc' => 'GASR870418JKL',
                'birth_date' => '1987-04-18',
                'hire_date' => '2019-09-01',
                'department_code' => 'FIN',
                'position_code' => 'ANAL-FIN',
                'user_email' => 'roberto.garcia@baglass.com',
                'address' => 'Calle Madero #789',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '06000',
            ],
            [
                'employee_number' => 'EMP-006',
                'first_name' => 'María Fernanda',
                'last_name' => 'Ruiz',
                'email' => 'maria.ruiz@baglass.com',
                'phone' => '(55) 7890-1234',
                'mobile' => '(55) 6666-7777',
                'curp' => 'RUFM950830MDFZRR04',
                'rfc' => 'RUFM950830MNO',
                'birth_date' => '1995-08-30',
                'hire_date' => '2022-01-10',
                'department_code' => 'MKT',
                'position_code' => 'DIS',
                'user_email' => 'maria.ruiz@baglass.com',
                'address' => 'Av. Chapultepec #234',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '06700',
            ],
            [
                'employee_number' => 'EMP-007',
                'first_name' => 'José Luis',
                'last_name' => 'Morales',
                'email' => 'jose.morales@baglass.com',
                'phone' => '(55) 8901-2345',
                'mobile' => '(55) 7777-8888',
                'curp' => 'MOJL880215HDFRRS06',
                'rfc' => 'MOJL880215PQR',
                'birth_date' => '1988-02-15',
                'hire_date' => '2020-06-01',
                'department_code' => 'TI',
                'position_code' => 'SOPORTE',
                'user_email' => 'jose.morales@baglass.com',
                'address' => 'Calle Juárez #567',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '06050',
            ],
            [
                'employee_number' => 'EMP-008',
                'first_name' => 'Patricia',
                'last_name' => 'Vega Ramírez',
                'email' => 'patricia.vega@baglass.com',
                'phone' => '(55) 9012-3456',
                'mobile' => '(55) 8888-9999',
                'curp' => 'VERP910505MDFGMT03',
                'rfc' => 'VERP910505STU',
                'birth_date' => '1991-05-05',
                'hire_date' => '2021-08-15',
                'department_code' => 'RH',
                'position_code' => 'RECL',
                'user_email' => null,
                'address' => 'Av. Patriotismo #890',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '03800',
            ],
            [
                'employee_number' => 'EMP-009',
                'first_name' => 'Fernando',
                'last_name' => 'Castro Díaz',
                'email' => 'fernando.castro@baglass.com',
                'phone' => '(55) 0123-4567',
                'mobile' => '(55) 9999-0000',
                'curp' => 'CADF860720HDFSRR01',
                'rfc' => 'CADF860720VWX',
                'birth_date' => '1986-07-20',
                'hire_date' => '2017-11-01',
                'department_code' => 'TI',
                'position_code' => 'DBA',
                'user_email' => null,
                'address' => 'Blvd. Ávila Camacho #123',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '11000',
            ],
            [
                'employee_number' => 'EMP-010',
                'first_name' => 'Gabriela',
                'last_name' => 'Mendoza Torres',
                'email' => 'gabriela.mendoza@baglass.com',
                'phone' => '(55) 1234-5670',
                'mobile' => '(55) 0000-1111',
                'curp' => 'METG930915MDFNRB08',
                'rfc' => 'METG930915YZA',
                'birth_date' => '1993-09-15',
                'hire_date' => '2022-04-01',
                'department_code' => 'VEN',
                'position_code' => 'COORD-VEN',
                'user_email' => null,
                'address' => 'Calle Durango #456',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '06700',
            ],
        ];

        foreach ($employees as $empData) {
            $department = Department::where('code', $empData['department_code'])->first();
            $position = Position::where('code', $empData['position_code'])->first();
            $user = $empData['user_email'] ? User::where('email', $empData['user_email'])->first() : null;

            Employee::create([
                'employee_number' => $empData['employee_number'],
                'first_name' => $empData['first_name'],
                'last_name' => $empData['last_name'],
                'email' => $empData['email'],
                'phone' => $empData['phone'],
                'mobile' => $empData['mobile'],
                'curp' => $empData['curp'],
                'rfc' => $empData['rfc'],
                'birth_date' => $empData['birth_date'],
                'hire_date' => $empData['hire_date'],
                'department_id' => $department->id,
                'position_id' => $position->id,
                'user_id' => $user?->id,
                'address' => $empData['address'],
                'city' => $empData['city'],
                'state' => $empData['state'],
                'postal_code' => $empData['postal_code'],
                'status' => 'active',
            ]);
        }
    }
}
