<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Equipment;
use App\Models\EquipmentCategory;
use App\Models\Location;
use App\Models\Supplier;
use App\Models\User;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('email', 'admin@baglass.com')->first();
        $laptopCategory = EquipmentCategory::where('code', 'LAPTOP')->first();
        $desktopCategory = EquipmentCategory::where('code', 'DESKTOP')->first();
        $monitorCategory = EquipmentCategory::where('code', 'MONITOR')->first();
        $almacenTI = Location::where('code', 'ALM-TI')->first();

        $dell = Brand::where('name', 'Dell')->first();
        $hp = Brand::where('name', 'HP')->first();
        $lenovo = Brand::where('name', 'Lenovo')->first();
        $apple = Brand::where('name', 'Apple')->first();

        $supplier1 = Supplier::where('code', 'PROV-001')->first();
        $supplier3 = Supplier::where('code', 'PROV-003')->first();

        $equipment = [
            // Laptops Dell
            [
                'internal_code' => 'EQ-2024-0001',
                'asset_tag' => 'ASSET-001',
                'category_id' => $laptopCategory->id,
                'brand_id' => $dell->id,
                'model' => 'Latitude 5540',
                'serial_number' => 'DELL5540ABC123',
                'processor' => 'Intel Core i7-1365U',
                'ram' => '16 GB DDR5',
                'storage' => '512 GB',
                'storage_type' => 'NVMe SSD',
                'screen_size' => '15.6"',
                'screen_resolution' => '1920x1080',
                'operating_system' => 'Windows 11 Pro',
                'os_version' => '23H2',
                'os_license_key' => 'XXXXX-XXXXX-XXXXX-XXXXX-XXXXX',
                'supplier_id' => $supplier3->id,
                'purchase_date' => '2024-01-15',
                'purchase_price' => 28500.00,
                'warranty_start_date' => '2024-01-15',
                'warranty_end_date' => '2027-01-15',
                'warranty_type' => 'ProSupport 3 años',
                'physical_condition' => 'excellent',
                'operational_status' => 'operational',
                'availability_status' => 'available',
                'location_id' => $almacenTI->id,
                'accessories' => 'Cargador original, mouse inalámbrico',
            ],
            [
                'internal_code' => 'EQ-2024-0002',
                'asset_tag' => 'ASSET-002',
                'category_id' => $laptopCategory->id,
                'brand_id' => $dell->id,
                'model' => 'Latitude 5540',
                'serial_number' => 'DELL5540DEF456',
                'processor' => 'Intel Core i7-1365U',
                'ram' => '16 GB DDR5',
                'storage' => '512 GB',
                'storage_type' => 'NVMe SSD',
                'screen_size' => '15.6"',
                'screen_resolution' => '1920x1080',
                'operating_system' => 'Windows 11 Pro',
                'os_version' => '23H2',
                'supplier_id' => $supplier3->id,
                'purchase_date' => '2024-01-15',
                'purchase_price' => 28500.00,
                'warranty_start_date' => '2024-01-15',
                'warranty_end_date' => '2027-01-15',
                'warranty_type' => 'ProSupport 3 años',
                'physical_condition' => 'excellent',
                'operational_status' => 'operational',
                'availability_status' => 'available',
                'location_id' => $almacenTI->id,
                'accessories' => 'Cargador original',
            ],
            // Laptops HP
            [
                'internal_code' => 'EQ-2024-0003',
                'asset_tag' => 'ASSET-003',
                'category_id' => $laptopCategory->id,
                'brand_id' => $hp->id,
                'model' => 'EliteBook 850 G10',
                'serial_number' => 'HP850G10XYZ789',
                'processor' => 'Intel Core i7-1355U',
                'ram' => '32 GB DDR5',
                'storage' => '1 TB',
                'storage_type' => 'NVMe SSD',
                'screen_size' => '15.6"',
                'screen_resolution' => '1920x1080',
                'operating_system' => 'Windows 11 Pro',
                'os_version' => '23H2',
                'supplier_id' => $supplier1->id,
                'purchase_date' => '2024-02-01',
                'purchase_price' => 35000.00,
                'warranty_start_date' => '2024-02-01',
                'warranty_end_date' => '2027-02-01',
                'warranty_type' => 'HP Care Pack 3 años',
                'physical_condition' => 'excellent',
                'operational_status' => 'operational',
                'availability_status' => 'available',
                'location_id' => $almacenTI->id,
                'accessories' => 'Cargador original, docking station',
            ],
            [
                'internal_code' => 'EQ-2024-0004',
                'asset_tag' => 'ASSET-004',
                'category_id' => $laptopCategory->id,
                'brand_id' => $hp->id,
                'model' => 'ProBook 450 G10',
                'serial_number' => 'HP450G10ABC123',
                'processor' => 'Intel Core i5-1335U',
                'ram' => '16 GB DDR4',
                'storage' => '512 GB',
                'storage_type' => 'NVMe SSD',
                'screen_size' => '15.6"',
                'screen_resolution' => '1920x1080',
                'operating_system' => 'Windows 11 Pro',
                'os_version' => '23H2',
                'supplier_id' => $supplier1->id,
                'purchase_date' => '2024-02-15',
                'purchase_price' => 22000.00,
                'warranty_start_date' => '2024-02-15',
                'warranty_end_date' => '2026-02-15',
                'warranty_type' => 'HP Care Pack 2 años',
                'physical_condition' => 'excellent',
                'operational_status' => 'operational',
                'availability_status' => 'available',
                'location_id' => $almacenTI->id,
                'accessories' => 'Cargador original',
            ],
            // Laptops Lenovo
            [
                'internal_code' => 'EQ-2024-0005',
                'asset_tag' => 'ASSET-005',
                'category_id' => $laptopCategory->id,
                'brand_id' => $lenovo->id,
                'model' => 'ThinkPad T14s Gen 4',
                'serial_number' => 'LENT14SGEN4001',
                'processor' => 'Intel Core i7-1365U',
                'ram' => '16 GB LPDDR5',
                'storage' => '512 GB',
                'storage_type' => 'NVMe SSD',
                'screen_size' => '14"',
                'screen_resolution' => '2880x1800',
                'operating_system' => 'Windows 11 Pro',
                'os_version' => '23H2',
                'supplier_id' => $supplier1->id,
                'purchase_date' => '2024-03-01',
                'purchase_price' => 32000.00,
                'warranty_start_date' => '2024-03-01',
                'warranty_end_date' => '2027-03-01',
                'warranty_type' => 'Premier Support 3 años',
                'physical_condition' => 'excellent',
                'operational_status' => 'operational',
                'availability_status' => 'available',
                'location_id' => $almacenTI->id,
                'accessories' => 'Cargador USB-C, funda',
            ],
            // MacBook
            [
                'internal_code' => 'EQ-2024-0006',
                'asset_tag' => 'ASSET-006',
                'category_id' => $laptopCategory->id,
                'brand_id' => $apple->id,
                'model' => 'MacBook Pro 14" M3 Pro',
                'serial_number' => 'APPMBP14M3PRO01',
                'processor' => 'Apple M3 Pro',
                'ram' => '18 GB',
                'storage' => '512 GB',
                'storage_type' => 'SSD',
                'screen_size' => '14.2"',
                'screen_resolution' => '3024x1964',
                'operating_system' => 'macOS Sonoma',
                'os_version' => '14.0',
                'supplier_id' => $supplier1->id,
                'purchase_date' => '2024-03-15',
                'purchase_price' => 52000.00,
                'warranty_start_date' => '2024-03-15',
                'warranty_end_date' => '2025-03-15',
                'warranty_type' => 'AppleCare+ 1 año',
                'physical_condition' => 'excellent',
                'operational_status' => 'operational',
                'availability_status' => 'available',
                'location_id' => $almacenTI->id,
                'accessories' => 'Cargador MagSafe, cable USB-C',
            ],
            // Equipos de escritorio
            [
                'internal_code' => 'EQ-2024-0007',
                'asset_tag' => 'ASSET-007',
                'category_id' => $desktopCategory->id,
                'brand_id' => $dell->id,
                'model' => 'OptiPlex 7010 SFF',
                'serial_number' => 'DELLOPT7010001',
                'processor' => 'Intel Core i7-13700',
                'ram' => '32 GB DDR5',
                'storage' => '512 GB',
                'storage_type' => 'NVMe SSD',
                'operating_system' => 'Windows 11 Pro',
                'os_version' => '23H2',
                'supplier_id' => $supplier3->id,
                'purchase_date' => '2024-01-20',
                'purchase_price' => 25000.00,
                'warranty_start_date' => '2024-01-20',
                'warranty_end_date' => '2027-01-20',
                'warranty_type' => 'ProSupport 3 años',
                'physical_condition' => 'excellent',
                'operational_status' => 'operational',
                'availability_status' => 'available',
                'location_id' => $almacenTI->id,
                'accessories' => 'Teclado, mouse',
            ],
            [
                'internal_code' => 'EQ-2024-0008',
                'asset_tag' => 'ASSET-008',
                'category_id' => $desktopCategory->id,
                'brand_id' => $hp->id,
                'model' => 'ProDesk 400 G9 SFF',
                'serial_number' => 'HPPD400G9001',
                'processor' => 'Intel Core i5-13500',
                'ram' => '16 GB DDR4',
                'storage' => '512 GB',
                'storage_type' => 'NVMe SSD',
                'operating_system' => 'Windows 11 Pro',
                'os_version' => '23H2',
                'supplier_id' => $supplier1->id,
                'purchase_date' => '2024-02-10',
                'purchase_price' => 18000.00,
                'warranty_start_date' => '2024-02-10',
                'warranty_end_date' => '2026-02-10',
                'warranty_type' => 'HP Care Pack 2 años',
                'physical_condition' => 'excellent',
                'operational_status' => 'operational',
                'availability_status' => 'available',
                'location_id' => $almacenTI->id,
                'accessories' => 'Teclado, mouse',
            ],
            // Monitores
            [
                'internal_code' => 'EQ-2024-0009',
                'asset_tag' => 'ASSET-009',
                'category_id' => $monitorCategory->id,
                'brand_id' => $dell->id,
                'model' => 'UltraSharp U2723QE',
                'serial_number' => 'DELLU2723QE001',
                'screen_size' => '27"',
                'screen_resolution' => '3840x2160',
                'supplier_id' => $supplier3->id,
                'purchase_date' => '2024-01-15',
                'purchase_price' => 12000.00,
                'warranty_start_date' => '2024-01-15',
                'warranty_end_date' => '2027-01-15',
                'warranty_type' => 'Premium Panel Exchange 3 años',
                'physical_condition' => 'excellent',
                'operational_status' => 'operational',
                'availability_status' => 'available',
                'location_id' => $almacenTI->id,
                'accessories' => 'Cable HDMI, cable USB-C, cable DisplayPort',
            ],
            [
                'internal_code' => 'EQ-2024-0010',
                'asset_tag' => 'ASSET-010',
                'category_id' => $monitorCategory->id,
                'brand_id' => $hp->id,
                'model' => 'E24 G5 FHD',
                'serial_number' => 'HPE24G5001',
                'screen_size' => '24"',
                'screen_resolution' => '1920x1080',
                'supplier_id' => $supplier1->id,
                'purchase_date' => '2024-02-01',
                'purchase_price' => 5500.00,
                'warranty_start_date' => '2024-02-01',
                'warranty_end_date' => '2027-02-01',
                'warranty_type' => 'HP 3 años',
                'physical_condition' => 'excellent',
                'operational_status' => 'operational',
                'availability_status' => 'available',
                'location_id' => $almacenTI->id,
                'accessories' => 'Cable HDMI, cable VGA',
            ],
        ];

        foreach ($equipment as $eq) {
            Equipment::create(array_merge($eq, [
                'created_by' => $admin->id,
                'updated_by' => $admin->id,
            ]));
        }
    }
}
